# Generated by Django 3.2.3 on 2022-10-25 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, editable=False)),
                ('date_of_birthday', models.DateField(default=datetime.datetime.now)),
                ('state', models.IntegerField(choices=[(1, 'Activo'), (0, 'Bloqueado')], default=1)),
                ('user', models.CharField(default=models.CharField(max_length=50), max_length=50)),
                ('date_register', models.DateField(default=datetime.datetime.now, editable=False)),
                ('date_modify', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.datetime.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
