# Generated by Django 3.2.3 on 2022-10-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addressclient_area_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude_home',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude_home',
            field=models.FloatField(default=0),
        ),
    ]
